// loaders
export const LOGIN_ENABLE_LOADER = "LOGIN_ENABLE_LOADER";
export const LOGIN_DISABLE_LOADER = "LOGIN_DISABLE_LOADER";

// login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

// logout
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// register
export const REGISTER_REQUEST = "REGISTER_REQUEST";
// export const UPDATE_USER = "UPDATE_USER";

// login Facebook
export const LOGINFB_REQUEST = "LOGINFB_REQUEST";

// login Google
export const LOGINGG_REQUEST = "LOGINGG_REQUEST";

// remove account
// export const REMOVE_USER_ACCOUNT = "REMOVE_USER_ACCOUNT"
// export const REMOVE_USER_ACCOUNT_SUCCESS = "REMOVE_USER_ACCOUNT_SUCCESS"


// change paaword
// export const CHANGE_PASSWORD ="CHANGE_PASSWORD"
// export const CHANGE_PASSWORD_SUCCESS ="CHANGE_PASSWORD_SUCCESS"


// UPDATE PROFILE
// export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE"
// export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFIUPDATE_USER_PROFILE_SUCCESSLE"
